GET http://localhost/animemaniatics/animes.php HTTP/1.1

###
POST http://localhost/animemaniatics/animes.php HTTP/1.1
Content-Type: "application/json"

{
    "options": {
        "action": "addEpisode",
        "object": "anime"
    },
    "id": 3,
    "name": "Kenja no Mago",
    "img": "https://s.pacn.ws/1500/nf/kenja-no-mago-joshikiyaburi-no-shinyusei-421689.1.jpg?o33g2h",
    "description": "La historia empieza cuando un poderoso brujo y sabio, que salvó al mundo de la calamidad en numerosas ocasiones, se encuentra un bebé al que adopta y nombra como Shin. El bebé es en realidad un hombre de nuestro mundo reencarnado en el mundo del sabio. Este cria a Shin lejos de la sociedad y le enseña los entresijos de la magia. Una vez cumple los 15 años, el joven emprende su propio viaje pero el sabio se acuerda entonces que se ha olvidado de enseñarle sobre el sentido común y la forma en que funciona la vida. Así pues, sin experiencia ninguna con las relaciones personales, Shin llega a la capital del reino de Alsheid para apuntarse a la academia de magia.",
    "caption": "Mago super OP",
    "status": "Emision",
    "release_date": "April 10th, 2019",
    "ended": "June 26th, 2019",
    "episodes": 11,
    "bg_img": "",
    "type": "anime",
    "tags": "Accion, Comedy, Fantasy, Magic",
    "ENG_name": "Philosopher's Grandson, Magi's Grandson",
    "hiragana_name": "賢者の孫",
    "second_ENG_name": ""
}

###
POST  http://localhost/animemaniatics/user.php HTTP/1.1
Content-Type: "application/json"

{
    "options": 
        {
            "method": "create",
            "action": "user"
        }
    ,
    "name": "Carlos",
    "lastName": "Ordonez",
    "email": "carlos@carlosdaniel.info",
    "password": "CarlosDUniPass#201",
    "account": ["hola", "adios"],
    "extra": [
        {"extra": 1},
        {"dos": 2}
    ]
}